version: '3'
services:
  server:
    build: server/
#      context: .
#    restart: always 
    ports:
      - "5001:5001"
    networks:
          iperf-client:
            ipv4_address: 192.168.73.3
    command: -u -s

  client:
    build: client/
#      context: .
#    restart: always
    networks:
         iperf-server:
            ipv4_address: 192.168.74.3
    command: -u -c $arg1 -p 5001 -b 30M  -t $arg2
    depends_on:
      - server

  client1:
    build: client/
#      context: .
#    restart: always
    networks:
         iperf-server:
            ipv4_address: 192.168.74.4
    command: -u -c $arg1 -p 5001:5003 -b 300M -t $arg2
    depends_on:
      - server
  client2:
    build: client/
#      context: .
#    restart: always
    networks:
         iperf-server:
            ipv4_address: 192.168.74.5
    command: -u -c $arg1 -p 5001:5004 -b 200M -t $arg2
    depends_on:
      - server
  client3:
    build: client/
#      context: .
#    restart: always
    networks:
         iperf-server:
            ipv4_address: 192.168.74.6
    command: -u -c $arg1 -p 5001:5004 -b 100M -t $arg2
    depends_on:
      - server


networks:
  iperf-client:
     external: true
  iperf-server:
     external: true
